package:
  name: grdtiler
  version: {{ environ.get('GIT_DESCRIBE_TAG', 0)}}

source:
  git_url: https://github.com/jean2262/grdtiler.git
  git_rev: HEAD  

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.10,<3.12
    - setuptools
    - setuptools_scm
    - pip
  host:
    - python >=3.10,<3.12
    - numpy
    - pytest
    - pytest-cov
    - tqdm
    - shapely
    - xarray
    - xsar
    - xarray-safe-s1
    - xradarsat2
    - xarray-safe-rcm
    - xsarsea
  run:
    - python >=3.10,<3.12
    - numpy
    - pytest
    - pytest-cov
    - tqdm
    - shapely
    - xarray
    - xsar
    - xarray-safe-s1
    - xradarsat2
    - xarray-safe-rcm
    - xsarsea

about:
  home: https://github.com/jean2262/grdtiler.git
  license: MIT
  summary: "A package for tiling GRD products"

extra:
  recipe-maintainers:
    - jean2262 
