name: grdtiler-test
channels:
  - conda-forge
dependencies:
    - numpy
    - pytest
    - pytest-cov
    - holoviews
    - cartopy
    - tqdm
    - shapely
    - xsar=2024.2.1
    - xsarsea
    - xsarslc
    - matplotlib
    - xarray-safe-s1
    - xradarsat2
    - xarray-safe-rcm

